name: Deploy MultiDocker
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t turtletomcat/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true turtletomcat/react-test npm test
 
      - run: docker build -t turtletomcat/multi-client-10-14 ./client
      - run: docker build -t turtletomcat/multi-nginx-10-14 ./nginx
      - run: docker build -t turtletomcat/multi-server-10-14 ./server
      - run: docker build -t turtletomcat/multi-worker-10-14 ./worker
 
      - run: docker push turtletomcat/multi-client-10-14
      - run: docker push turtletomcat/multi-nginx-10-14
      - run: docker push turtletomcat/multi-server-10-14
      - run: docker push turtletomcat/multi-worker-10-14
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: complex
          environment_name: Complex-env
          existing_bucket_name: elasticbeanstalk-us-east-1-733936996857
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip